name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install dependencies
      run: make deps
    
    - name: Lint
      run: make lint
    
    - name: Build
      run: make build
    
    - name: Run unit tests
      run: make test
    
    - name: Run tests with coverage
      run: make test-coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        fail_ci_if_error: false
    
    - name: Install expect for E2E tests
      run: sudo apt-get update && sudo apt-get install -y expect
    
    - name: Run E2E tests
      run: make test-e2e
    
    - name: Security audit
      run: make audit

  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run integration tests
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_URL: https://gitlab.com
      run: |
        if [ -n "$GITLAB_TOKEN" ]; then
          make test-integration
        else
          echo "GITLAB_TOKEN not set, skipping integration tests"
        fi
